[template]
src = "bugzilla-localconfig.tmpl"
dest = "/var/www/bugzilla/localconfig.confd"
prefix = "/%%STACK%%/%%ENVIRONMENT%%"

uid = 0
gid = 48
mode = "0640"

keys = [
    "/config"
]

reload_cmd = "/usr/local/bin/bugzilla-update"
